export const SET_CLIENT = 'SET_CLIENT';
export const SET_ACCOUNTS = 'SET_ACCOUNTS'
export const SET_WITNESSES = 'SET_WITNESSES';
export const SET_EXCHANGE_RATES = 'SET_EXCHANGE_RATES';
export const SET_ASSETS_NAME_AND_DECIMALS = 'SET_ASSETS_NAME_AND_DECIMALS';
export const SET_BALANCES = 'SET_BALANCES';
